export const INITIAL_ROAD_CONTRACTORS = [
  {
    id: 'CTR-NHAI-001',
    contractorName: 'Rajesh Sharma',
    companyName: 'ABC Infrastructure Pvt Ltd',
    assignedRoads: ['NH-48 Sector 21', 'MG Road Corridor', 'Cyber City Underpass'],
    activeProjectsCount: 3,
    completedRepairsCount: 142,
    phone: '+91 98110 44219',
    email: 'operations@abcinfra.com',
    maintenanceStartDate: '01 Jan 2026',
    maintenanceExpiryDate: '31 Dec 2027',
    contractStatus: 'active' as const,
    zone: 'Zone 1 (National Highway)',
    slaAdherenceRate: 98.4,
  },
  {
    id: 'CTR-NHAI-002',
    contractorName: 'Vikram Choudhury',
    companyName: 'Apex Roadworks & Civil Tech',
    assignedRoads: ['Outer Ring Road (ORR)', 'Sarjapur Junction', 'Whitefield Main Road'],
    activeProjectsCount: 5,
    completedRepairsCount: 89,
    phone: '+91 98450 11982',
    email: 'contracts@apexroadworks.in',
    maintenanceStartDate: '15 Feb 2025',
    maintenanceExpiryDate: '15 Oct 2026',
    contractStatus: 'expiring_soon' as const,
    zone: 'Zone 3 (Urban Corridor)',
    slaAdherenceRate: 91.2,
  },
 
  {
    id: 'CTR-NHAI-004',
    contractorName: 'Suresh Patil',
    companyName: 'Sahyadri Bitumen & Infra',
    assignedRoads: ['Western Express Highway', 'SV Road Bandra', 'Link Road Andheri'],
    activeProjectsCount: 0,
    completedRepairsCount: 65,
    phone: '+91 98200 33891',
    email: 'admin@sahyadriinfra.in',
    maintenanceStartDate: '01 Mar 2024',
    maintenanceExpiryDate: '28 Feb 2026',
    contractStatus: 'expired' as const,
    zone: 'Zone 2 (Western Metro)',
    slaAdherenceRate: 84.5,
  },
];

export const INITIAL_REPORTS = [
  {
    id: 'RG-2026-0891',
    title: 'Severe crater near NH-48 toll plaza exit',
    description: 'Deep pavement cavity formed due to water accumulation and heavy truck transit. Severe risk of two-wheeler skidding and tyre blowout.',
    imageUrl: 'https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&w=800&q=80',
    severity: 'severe' as const,
    priority: 'critical' as const,
    status: 'assigned' as const,
    confidenceScore: 96,
    location: {
      address: 'Near NH-48 Sector 21 Junction, Milestone 42, Gurugram NCR',
      roadName: 'NH-48 Sector 21',
      city: 'Gurugram',
      state: 'Haryana',
      lat: 28.4595,
      lng: 77.0266,
      landmark: 'Opposite Ambience Tower',
    },
    reportedBy: {
      name: 'Rohan Sharma',
      phone: '+91 98765 43210',
      citizenId: 'CIT-DEL-9941',
    },
    assignedContractorId: 'CTR-NHAI-001',
    assignedContractorName: 'ABC Infrastructure Pvt Ltd',
    reportedAt: '11 Sep 2026, 09:30 AM',
    assignedAt: '11 Sep 2026, 11:00 AM',
    deadline: '12 Sep 2026, 06:00 PM',
    aiAnalysis: {
      detected: true,
      detectedCount: 2,
      confidenceScore: 96,
      severity: 'severe' as const,
      boundingBoxes: [
        { x: 26, y: 32, width: 48, height: 42 },
        { x: 76, y: 52, width: 16, height: 18 },
      ],
      estimatedDimensions: {
        widthCm: 82,
        depthCm: 15.2,
        areaSqM: 0.65,
      },
      roadCondition: 'Crater with exposed ballast aggregates; severe two-wheeler flip hazard',
      recommendedUrgency: 'Emergency cold mix asphalt filling required within 24 hours',
    },
    timeline: [
      {
        status: 'reported' as const,
        timestamp: '11 Sep 2026, 09:30 AM',
        title: 'Pothole Reported by Citizen',
        description: 'Image and GPS coordinates captured via RoadGuard AI client.',
        actor: 'Citizen (Rohan Sharma)',
      },
      {
        status: 'verified' as const,
        timestamp: '11 Sep 2026, 10:15 AM',
        title: 'Verified by Highway Control Desk',
        description: 'AI detection confirmed 96% confidence score and classified as Severe Hazard.',
        actor: 'NHAI Control Center',
      },
      {
        status: 'assigned' as const,
        timestamp: '11 Sep 2026, 11:00 AM',
        title: 'Assigned to Road Contractor',
        description: 'Assigned to ABC Infrastructure Pvt Ltd under active DLP maintenance contract.',
        actor: 'Divisional Engineer, PWD',
      },
    ],
  },
  {
    id: 'RG-2026-0892',
    title: 'Moderate surface cavitation on Outer Ring Road',
    description: 'Wearing course bitumen peeling off, producing a 8cm depression in the middle vehicular lane.',
    imageUrl: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=800&q=80',
    severity: 'moderate' as const,
    priority: 'urgent' as const,
    status: 'in_progress' as const,
    confidenceScore: 93,
    location: {
      address: 'Outer Ring Road, Near Bellandur Flyover Pillar 56, Bengaluru',
      roadName: 'Outer Ring Road',
      city: 'Bengaluru',
      state: 'Karnataka',
      lat: 12.9352,
      lng: 77.6836,
      landmark: 'Near EcoSpace Tech Park',
    },
    reportedBy: {
      name: 'Priya Iyer',
      phone: '+91 98450 88721',
      citizenId: 'CIT-BLR-4012',
    },
    assignedContractorId: 'CTR-NHAI-002',
    assignedContractorName: 'Apex Roadworks & Civil Tech',
    reportedAt: '10 Sep 2026, 04:15 PM',
    assignedAt: '10 Sep 2026, 06:00 PM',
    deadline: '13 Sep 2026, 08:00 PM',
    aiAnalysis: {
      detected: true,
      detectedCount: 1,
      confidenceScore: 93,
      severity: 'moderate' as const,
      boundingBoxes: [{ x: 32, y: 38, width: 38, height: 34 }],
      estimatedDimensions: {
        widthCm: 52,
        depthCm: 8.4,
        areaSqM: 0.32,
      },
      roadCondition: 'Base layer cavitation triggered by monsoon water logging',
      recommendedUrgency: 'Milling and binder course application required in 48 hours',
    },
    timeline: [
      {
        status: 'reported' as const,
        timestamp: '10 Sep 2026, 04:15 PM',
        title: 'Reported by Citizen',
        description: 'Captured via RoadGuard live road camera.',
        actor: 'Citizen (Priya Iyer)',
      },
      {
        status: 'verified' as const,
        timestamp: '10 Sep 2026, 05:00 PM',
        title: 'Automated AI Verification',
        description: 'Classified as Moderate damage with 93% accuracy.',
        actor: 'RoadGuard Vision Engine',
      },
      {
        status: 'assigned' as const,
        timestamp: '10 Sep 2026, 06:00 PM',
        title: 'Contractor Dispatched',
        description: 'Work order dispatched to Apex Roadworks & Civil Tech.',
        actor: 'BBMP Road Safety Cell',
      },
      {
        status: 'in_progress' as const,
        timestamp: '11 Sep 2026, 08:00 AM',
        title: 'Repair Underway',
        description: 'Road milling machine and cold-mix bitumen team mobilized on-site.',
        actor: 'Apex Roadworks Ground Crew',
      },
    ],
  },
  {
    id: 'RG-2026-0888',
    title: 'Repaired road strip on Ashram Flyover descent',
    description: 'Edge raveling and shallow pothole previously reported and successfully restored with hot-mix asphalt.',
    imageUrl: 'https://images.unsplash.com/photo-1578885136359-16c8bd4d3a8e?auto=format&fit=crop&w=800&q=80',
    severity: 'minor' as const,
    priority: 'normal' as const,
    status: 'completed' as const,
    confidenceScore: 89,
    location: {
      address: 'Ring Road, Ashram Flyover Eastern Ramp, New Delhi',
      roadName: 'Ring Road Ashram Flyover',
      city: 'New Delhi',
      state: 'Delhi',
      lat: 28.5714,
      lng: 77.2588,
      landmark: 'Near Ashram Metro Station Gate 2',
    },
    reportedBy: {
      name: 'Anil Verma',
      phone: '+91 99100 22345',
      citizenId: 'CIT-DEL-1029',
    },
    assignedContractorId: 'CTR-NHAI-001',
    assignedContractorName: 'ABC Infrastructure Pvt Ltd',
    reportedAt: '08 Sep 2026, 11:20 AM',
    assignedAt: '08 Sep 2026, 02:00 PM',
    deadline: '10 Sep 2026, 06:00 PM',
    repairNotes: 'Bituminous hot-mix asphalt laid and roller compacted. Passed IRI roughness and rideability test.',
    aiAnalysis: {
      detected: true,
      detectedCount: 1,
      confidenceScore: 89,
      severity: 'minor' as const,
      boundingBoxes: [{ x: 40, y: 44, width: 26, height: 22 }],
      estimatedDimensions: {
        widthCm: 34,
        depthCm: 4.5,
        areaSqM: 0.16,
      },
      roadCondition: 'Surface raveling successfully sealed',
      recommendedUrgency: 'Quality audit certified',
    },
    timeline: [
      {
        status: 'reported' as const,
        timestamp: '08 Sep 2026, 11:20 AM',
        title: 'Reported',
        description: 'Report lodged with image.',
        actor: 'Citizen (Anil Verma)',
      },
      {
        status: 'verified' as const,
        timestamp: '08 Sep 2026, 12:00 PM',
        title: 'Verified',
        description: 'Verified by PWD Road Safety Unit.',
        actor: 'PWD Officer',
      },
      {
        status: 'assigned' as const,
        timestamp: '08 Sep 2026, 02:00 PM',
        title: 'Assigned',
        description: 'Assigned to ABC Infrastructure.',
        actor: 'Authority Desk',
      },
      {
        status: 'in_progress' as const,
        timestamp: '09 Sep 2026, 09:30 AM',
        title: 'Repair Started',
        description: 'Bitumen patch repair begun.',
        actor: 'ABC Infra Crew',
      },
      {
        status: 'completed' as const,
        timestamp: '10 Sep 2026, 04:00 PM',
        title: 'Repair Completed & Quality Certified',
        description: 'Asphalt compaction passed engineering standards. Case closed.',
        actor: 'PWD Quality Auditor',
      },
    ],
  },
];
